{
 "title": "Kafka Cluster Monitoring Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Kafka Cluster Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions topic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "messages" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\"})"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "controller" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUM(kafka_controller_kafkacontroller_value{name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Leader count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_value{name=\"LeaderCount\", instance=\"server01:7071\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "kafka_server_replicamanager_value{name=\"LeaderCount\", instance=\"server02:7071\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "kafka_server_replicamanager_value{name=\"LeaderCount\", instance=\"server03:7071\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Car_info Topic BytesIn and BytesOut",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"server01:7071\",name=\"BytesInPerSec\", topic=\"car_info\"}",
     "legendFormat": "Server01-BytesInPerSec"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"server02:7071\",name=\"BytesInPerSec\", topic=\"car_info\"}",
     "legendFormat": "Server02-BytesInPerSec"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"server03:7071\",name=\"BytesInPerSec\", topic=\"car_info\"}",
     "legendFormat": "Server03-BytesInPerSec"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"server01:7071\",name=\"BytesOutPerSec\"}",
     "legendFormat": "Server01-BytesOutPerSec"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"server02:7071\",name=\"BytesOutPerSec\"}",
     "legendFormat": "Server02-BytesOutPerSec"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{instance=\"server03:7071\",name=\"BytesOutPerSec\"}",
     "legendFormat": "Server03-BytesOutPerSec"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "partitions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_value{instance=\"server01:7071\",name=\"GlobalPartitionCount\"}"
    }
   ]
  },
  {
   "title": "Total Under Replicated Partition Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "under replicated" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Total Offline Partitions Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "offline partitions" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_value{name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "Max lag in messages btw follower and leader replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_value{instance=\"server01:7071\",name=\"MaxLag\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "kafka_server_replicafetchermanager_value{instance=\"server02:7071\",name=\"MaxLag\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "kafka_server_replicafetchermanager_value{instance=\"server03:7071\",name=\"MaxLag\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Kafka Network Request Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "SUM(kafka_network_requestmetrics_count{instance=\"server01:7071\",job=\"kafka-brokers\",name=\"RequestsPerSec\"})",
     "legendFormat": "Server01"
    },
    {
     "expr": "SUM(kafka_network_requestmetrics_count{instance=\"server02:7071\",job=\"kafka-brokers\",name=\"RequestsPerSec\"})",
     "legendFormat": "Server02"
    },
    {
     "expr": "SUM(kafka_network_requestmetrics_count{instance=\"server03:7071\",job=\"kafka-brokers\",name=\"RequestsPerSec\"})",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Request Handler Load (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kafka_server_kafkarequesthandlerpool_oneminuterate{instance=\"server01:7071\",name=\"RequestHandlerAvgIdlePercent\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "1 - kafka_server_kafkarequesthandlerpool_oneminuterate{instance=\"server02:7071\",name=\"RequestHandlerAvgIdlePercent\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "1 - kafka_server_kafkarequesthandlerpool_oneminuterate{instance=\"server03:7071\",name=\"RequestHandlerAvgIdlePercent\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Network Processor Load (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(kafka_network_processor_value{instance=\"server01:7071\",name=\"IdlePercent\"})",
     "legendFormat": "Server01"
    },
    {
     "expr": "1 - avg(kafka_network_processor_value{instance=\"server02:7071\",name=\"IdlePercent\"})",
     "legendFormat": "Server02"
    },
    {
     "expr": "1 - avg(kafka_network_processor_value{instance=\"server03:7071\",name=\"IdlePercent\"})",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Zookeeper Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "avg_latency{instance=\"server01:7070\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "avg_latency{instance=\"server02:7070\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "avg_latency{instance=\"server03:7070\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "watch_count{instance=\"server01:7070\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "watch_count{instance=\"server02:7070\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "watch_count{instance=\"server03:7070\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Zookeeper Up Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"server01:7070\",job=\"zookeeper\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "up{instance=\"server02:7070\",job=\"zookeeper\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "up{instance=\"server03:7070\",job=\"zookeeper\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Active connections count",
   "type": "stat",
   "description": "Active connections on Zookeeper",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "num_alive_connections{instance=\"server01:7070\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "num_alive_connections{instance=\"server02:7070\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "num_alive_connections{instance=\"server03:7070\"}",
     "legendFormat": "Server03"
    },
    {}
   ]
  },
  {
   "title": "Leader election happens",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(election_time_count{instance=\"server01:7070\"}[5m])",
     "legendFormat": "Server01"
    },
    {
     "expr": "rate(election_time_count{instance=\"server02:7070\"}[5m])",
     "legendFormat": "Server02"
    },
    {
     "expr": "rate(election_time_count{instance=\"server03:7070\"}[5m])",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Znode Total Occupied Memory Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "approximate_data_size{instance=\"server01:7070\"}/1024/1024",
     "legendFormat": "Server01"
    },
    {
     "expr": "approximate_data_size{instance=\"server02:7070\"}/1024/1024",
     "legendFormat": "Server02"
    },
    {
     "expr": "approximate_data_size{instance=\"server03:7070\"}/1024/1024",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "Znode count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "nodes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "znode_count{instance=\"server01:7070\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "znode_count{instance=\"server02:7070\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "znode_count{instance=\"server03:7070\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  { "title": "JVM Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{instance=\"server01:7071\",job=\"kafka-brokers\"}",
     "legendFormat": "Server01"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_used{instance=\"server02:7071\",job=\"kafka-brokers\"}",
     "legendFormat": "Server02"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_used{instance=\"server03:7071\",job=\"kafka-brokers\"}",
     "legendFormat": "Server03"
    }
   ]
  },
  {
   "title": "JVM System CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcpuload{instance=~\"server01:7071|server02:7071|server03:7071\",job=\"kafka-brokers\"}"
    }
   ]
  }
 ]
}